
document.addEventListener('DOMContentLoaded', () => {
 const nav=document.getElementById('nav');document.getElementById('hamb')?.addEventListener('click',()=>nav.classList.toggle('open'));
 function stars(canvasId,countFactor,alpha){const c=document.getElementById(canvasId);if(!c)return;const x=c.getContext('2d');let a=[];function r(){c.width=innerWidth;c.height=innerHeight;a=Array.from({length:Math.min(320,Math.floor(innerWidth*innerHeight/countFactor))},()=>({x:Math.random()*c.width,y:Math.random()*c.height,r:Math.random()*1.25+.2,o:Math.random()*.65+.1,v:Math.random()*.012+.003}))}function d(){x.clearRect(0,0,c.width,c.height);for(const s of a){s.o+=(Math.random()>.5?1:-1)*s.v;s.o=Math.max(.08,Math.min(.82,s.o));x.globalAlpha=s.o*alpha;x.fillStyle='#fff';x.beginPath();x.arc(s.x,s.y,s.r,0,Math.PI*2);x.fill()}x.globalAlpha=1;requestAnimationFrame(d)}r();d();addEventListener('resize',r)}stars('starfield',6000,1);stars('dustfield',12000,.42);
 document.querySelectorAll('[data-count]').forEach(el=>{const target=Number(el.dataset.count);const st=performance.now();function tick(n){const t=Math.min(1,(n-st)/1200);el.textContent=Math.floor(target*(1-Math.pow(1-t,3))).toLocaleString();if(t<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)});
 const nameInput=document.getElementById('captainName'),saveName=document.getElementById('saveCaptain'),novaText=document.getElementById('novaText'),mouth=document.getElementById('mouthPulse');const saved=localStorage.getItem('spacenovax_captain_name');if(saved&&nameInput){nameInput.value=saved;novaText.innerHTML=`Welcome back, Captain ${saved}.<br>Mining systems online.<br>Mission briefing available.`}saveName?.addEventListener('click',()=>{const n=(nameInput.value||'').trim();if(n){localStorage.setItem('spacenovax_captain_name',n);novaText.innerHTML=`Welcome back, Captain ${n}.<br>Your systems are ready.`;speakNova(true)}});
 function voice(){const v=speechSynthesis.getVoices();return v.find(x=>/female|zira|samantha|google us english/i.test(x.name))||v.find(x=>/en/i.test(x.lang))||v[0]}function speakNova(short=false){if(!('speechSynthesis'in window)){alert('This browser does not support voice.');return}const cap=localStorage.getItem('spacenovax_captain_name')||'';const hi=cap?`Welcome back, Captain ${cap}.`:'Welcome aboard, Captain.';const text=short?`${hi} Your SpaceNovaX systems are online.`:`${hi} I am Nova, your AI Fleet Commander. Mining systems are online. Today's mission is ready. Shall we begin our journey?`;speechSynthesis.cancel();const msg=new SpeechSynthesisUtterance(text);msg.lang='en-US';msg.rate=.92;msg.pitch=1.08;const vc=voice();if(vc)msg.voice=vc;msg.onstart=()=>mouth?.classList.add('speaking');msg.onend=()=>mouth?.classList.remove('speaking');speechSynthesis.speak(msg)}document.getElementById('novaSpeak')?.addEventListener('click',()=>speakNova(false));document.getElementById('novaStop')?.addEventListener('click',()=>{speechSynthesis.cancel();mouth?.classList.remove('speaking')});if('speechSynthesis'in window)speechSynthesis.onvoiceschanged=voice;
 let greeted=sessionStorage.getItem('spacenovax_nova_greeted')==='1';function first(){if(greeted)return;greeted=true;sessionStorage.setItem('spacenovax_nova_greeted','1');setTimeout(()=>speakNova(false),600);removeEventListener('pointerdown',first)}addEventListener('pointerdown',first);
 const panel=document.getElementById('novaPanel'),handle=document.getElementById('novaDragHandle');if(panel&&handle){const savedPos=localStorage.getItem('spacenovax_nova_panel_position');if(savedPos){try{const p=JSON.parse(savedPos);panel.classList.add('is-floating');panel.style.left=p.left+'px';panel.style.top=p.top+'px'}catch(e){}}let drag=false,sx=0,sy=0,sl=0,st=0;const clamp=(v,min,max)=>Math.max(min,Math.min(max,v));function begin(x,y){const r=panel.getBoundingClientRect();panel.classList.add('is-floating');panel.style.left=r.left+'px';panel.style.top=r.top+'px';drag=true;sx=x;sy=y;sl=r.left;st=r.top}function move(x,y){if(!drag)return;const r=panel.getBoundingClientRect();panel.style.left=clamp(sl+x-sx,8,Math.max(8,innerWidth-r.width-8))+'px';panel.style.top=clamp(st+y-sy,8,Math.max(8,innerHeight-r.height-8))+'px'}function end(){if(!drag)return;drag=false;const r=panel.getBoundingClientRect();localStorage.setItem('spacenovax_nova_panel_position',JSON.stringify({left:r.left,top:r.top}))}handle.addEventListener('mousedown',e=>{e.preventDefault();begin(e.clientX,e.clientY)});addEventListener('mousemove',e=>move(e.clientX,e.clientY));addEventListener('mouseup',end);handle.addEventListener('touchstart',e=>{const t=e.touches[0];if(t)begin(t.clientX,t.clientY)},{passive:false});addEventListener('touchmove',e=>{const t=e.touches[0];if(t)move(t.clientX,t.clientY)},{passive:false});addEventListener('touchend',end);handle.addEventListener('dblclick',()=>{localStorage.removeItem('spacenovax_nova_panel_position');panel.classList.remove('is-floating');panel.style.left='';panel.style.top=''})}
 document.documentElement.style.overflowX='hidden';document.body.style.overflowX='hidden';
});
